### ISSUE TITLE
[Provider Audit] provider.brixzen.my.id

### ISSUE THREAD

**Issue by brixzen** [akash-network/community#658]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community
  info:
    email: "<your email>"
    website: "<your website>"

```

[Ref documentation:](https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-5---domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-11---firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name : Ali Usman
2. Discord : usman.brixzen AND Telegram : brixzen
3. Contact email address : admin@brixzen.com

**Comment by shimpa1** [comment]
hi @brixzen ,

Provider responding to https status endpoint: yes
Provider responding to grpc status endpoint: yes
**Provider responding to orders: no** - Check the status of the RPC node your provider is using to communicate with the network.

Currently set attributes:
provider-services query provider get akash1ylcl54t38pw8hg2ehvs84r9jnwlfrxd7e889wk
attributes:
- key: organization
  value: Brixzen
- key: email
  value: admin@brixzen.com
**- key: host
  value: brixzen.my.id**
- key: website
  value: https://brixzen.com
- key: status-page
  value: https://stats.uptimerobot.com/prnen1hvFA
- key: location-region
  value: as-southeast
- key: country
  value: ID
- key: city
  value: MLG
- key: timezone
  value: utc+7
- key: location-type
  value: office
- key: hosting-provider
  value: brixzen
- key: capabilities/cpu
  value: intel
- key: capabilities/memory
  value: ddr3ecc
- key: network-provider
  value: firstmedia
- key: network-speed-up
  value: "100"
- key: network-speed-down
  value: "100"
- key: tier
  value: community
- key: region
  value: ap-southeast
- key: arch
  value: amd64
- key: host_uri
  value: https://provider.brixzen.my.id:8443
- key: info
  value: Brixzen hosting provider with high avability
- key: owner
  value: akash1ylcl54t38pw8hg2ehvs84r9jnwlfrxd7e889wk
host_uri: https://provider.brixzen.my.id:8443
**info:
  email: ""
  website: ""**
owner: akash1ylcl54t38pw8hg2ehvs84r9jnwlfrxd7e889wk

**Attributes correct: no
- key: host
  value: brixzen.my.id
Change value: to "akash"**

Add the following to the bottom of the ~/provider/provider.yaml file
**email: admin@brixzen.com
website: https://brixzen.com**

Then run `helm upgrade --install akash-provider akash/provider -n akash-services -f provider.yaml --set bidpricescript="$(cat ~/provider/price_script_generic.sh | openssl base64 -A)"`

Please fix these issues then we can continue.

thank you!

Shimpa

**Comment by brixzen** [comment]
Hi @shimpa1 

update of attribute done, but can't run akash start command, i install using praetor
this is the error message : 


```
akash start
INF initializing upgrade `akash_v0.15.0_cosmos_v0.44.x`
INF initializing upgrade `v0.20.0`
INF initializing upgrade `v0.26.0`
INF initializing upgrade `v0.28.0`
INF initializing upgrade `v0.30.0`
INF initializing upgrade `v0.32.0`
INF initializing upgrade `v0.34.0`
INF initializing upgrade `v0.24.0`
INF starting node with ABCI Tendermint in-process
INF service start impl=multiAppConn module=proxy msg={}
INF service start connection=query impl=localClient module=abci-client msg={}
INF service start connection=snapshot impl=localClient module=abci-client msg={}
INF service start connection=mempool impl=localClient module=abci-client msg={}
INF service start connection=consensus impl=localClient module=abci-client msg={}
INF service start impl=EventBus module=events msg={}
INF service start impl=PubSub module=pubsub msg={}
INF service start impl=IndexerService module=txindex msg={}
INF ABCI Handshake App Info hash="\x04\at�/�\x10>�۟bҘ v�\x0eN��ōO�ר\x01�z��" height=17650083 module=consensus protocol-version=0 software-version=v0.34.1
INF ABCI Replay Blocks appHeight=17650083 module=consensus stateHeight=17650083 storeHeight=17650084
INF Replay last block using real app module=consensus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x155746d]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0xc0000559c8, 0x14}, 0xc0002ceb40, {0x2c3dff8, 0xc000f93e40}, {0x2c6af30, 0xc0003dc800}, 0xc0013698f0, {0x2c387a0, 0xc0001b4a80}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.16/x/upgrade/abci.go:38 +0xfcd
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.45.16/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x2c5a798, 0x3fd8de0}, {0x2c6a0c8, 0xc000e3d840}, {{0xb, 0x0}, {0xc0002c5290, 0xa}, 0x10d51a4, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.16/types/module/module.go:491 +0x19d
github.com/akash-network/node/app.(*AkashApp).BeginBlocker(_, {{0x2c5a798, 0x3fd8de0}, {0x2c6a0c8, 0xc000e3d840}, {{0xb, 0x0}, {0xc0002c5290, 0xa}, 0x10d51a4, ...}, ...}, ...)
	github.com/akash-network/node/app/app.go:536 +0x39b
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc0010e7440, 0x20, 0x20}, {{0xb, 0x0}, {0xc0002c5290, 0xa}, 0x10d51a4, {0x1371d9fe, ...}, ...}, ...})
	github.com/cosmos/cosmos-sdk@v0.45.16/baseapp/abci.go:177 +0x9db
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc0010e7440, 0x20, 0x20}, {{0xb, 0x0}, {0xc0002c5290, 0xa}, 0x10d51a4, {0x1371d9fe, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.27/abci/client/local_client.go:280 +0xfe
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc0010e7440, 0x20, 0x20}, {{0xb, 0x0}, {0xc0002c5290, 0xa}, 0x10d51a4, {0x1371d9fe, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.27/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2c5a728?, 0xc0005075e0}, {0x2c63290, 0xc000f75900}, 0xc0003585a0, {0x2c6b3c8, 0xc000120b88}, 0x10d51a3?)
	github.com/tendermint/tendermint@v0.34.27/state/execution.go:307 +0x51d
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0002c4007, 0x7}}, {0xc0002c4090, 0xa}, 0x1, 0x10d51a3, {{0xc000160740, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/state/execution.go:140 +0x16b
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc0002c4007, 0x7}}, {0xc0002c4090, 0xa}, 0x1, 0x10d51a3, {{0xc000160740, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc0002c4007, 0x7}}, {0xc0002c4090, 0xa}, 0x1, 0x10d51a3, {{0xc000160740, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/consensus/replay.go:416 +0x73a
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000e51bc0, {0x2c6ca08, 0xc000492680})
	github.com/tendermint/tendermint@v0.34.27/consensus/replay.go:268 +0x3a8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc0002c4007, 0x7}}, {0xc0002c4090, 0xa}, 0x1, 0x10d51a3, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/node/node.go:329 +0x199
github.com/tendermint/tendermint/node.NewNode(0xc0000ed2c0, {0x2c41b40, 0xc0011da780}, 0xc0010569a0, {0x2c36a00, 0xc000012bd0}, 0x0?, 0x0?, 0xc000e529a8, {0x2c5a728, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/node/node.go:779 +0x557
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x2c5fed0, 0xc00049cf80}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.16/server/start.go:280 +0x897
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00105fb00?, {0x3fd8de0?, 0x0?, 0x0?})
	github.com/cosmos/cosmos-sdk@v0.45.16/server/start.go:128 +0x1e8
github.com/spf13/cobra.(*Command).execute(0xc00109a300, {0x3fd8de0, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004900)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/akash-network/node/cmd/akash/cmd.Execute(0x3efed98?, {0x22eea3a, 0x5})
	github.com/akash-network/node/cmd/akash/cmd/root.go:113 +0x1e8
main.main()
	github.com/akash-network/node/cmd/akash/main.go:17 +0x25
```

**Comment by brixzen** [comment]
i think found something here, why provider responding to orders: no, 
<img width="1552" alt="Screenshot 2024-08-20 at 02 05 57" src="https://github.com/user-attachments/assets/a59ffac4-e79e-4927-bdfe-9cd7ba57fb6e">
because of my wallet used as deployment orders before. i will try to update first. an re-run the setup. 

thanks @shimpa1

**Comment by brixzen** [comment]
done now, hopefully will be working now @shimpa1 i also changed the key using new wallet. thanks..

provider-services query provider get akash142cqa0uzcmjk8dpfd2lmcvpkr4jdxtstnguh48
attributes:
- key: organization
  value: Brixzen
- key: email
  value: admin@brixzen.com
- key: host
  value: akash
- key: website
  value: https://brixzen.com
- key: status-page
  value: https://stats.uptimerobot.com/prnen1hvFA
- key: location-region
  value: as-southeast
- key: country
  value: ID
- key: city
  value: MLG
- key: timezone
  value: utc+7
- key: location-type
  value: office
- key: hosting-provider
  value: brixzen
- key: capabilities/cpu
  value: intel
- key: capabilities/memory
  value: ddr3ecc
- key: network-provider
  value: firstmedia
- key: network-speed-up
  value: "100"
- key: network-speed-down
  value: "100"
- key: tier
  value: community
- key: region
  value: ap-southeast
- key: arch
  value: amd64
- key: host_uri
  value: https://provider.brixzen.my.id:8443
host_uri: https://provider.brixzen.my.id:8443
info:
  email: admin@brixzen.com
  website: https://brixzen.com
owner: akash142cqa0uzcmjk8dpfd2lmcvpkr4jdxtstnguh48

**Comment by shimpa1** [comment]
@andy108369 
Provider akash1ylcl54t38pw8hg2ehvs84r9jnwlfrxd7e889wkready to be signed

**Comment by andy108369** [comment]
Tested (with dseq 17693194)

[Signed](https://www.mintscan.io/akash/tx/D9133BEF102810072A429DC2D11172B008B230F85D28225FD0524BCBBD08F1E2)

FWIW: the `email` & `website` do not need to be provider attributes, but just the `info` fields only.
